### ISSUE TITLE
Précisions 

### ISSUE THREAD

**Issue by Cardiacman13** [Xdavius/postinstall-debian#45]
Yo Dav suite à la vidéo que nous avons faites ensemble,

Je pense que il faut que tu ajoutes des "recommandé" en vert et des "Warning" en rouge. 

+ Que tu ajoutes quelque mots, par exemple ne pas marquer "Debian Stable" quand c'est compatible uniquement avec Debian Stable mais marquer "Compatible uniquement Debian Stable".

Même moi qui suis pas mal habitué je pense que j'aurais fais des bêtises sans toi. Par exemple à la fin du script sécure boot faut que le script il bloque et fasse un truc du même style que le mien avec : 

```bash
echo -e "${RED}Le script est terminé, le système doit redémarrer${RESET} : Appuyez sur ${GREEN}Entrée${RESET} pour redémarrer ou ${GREEN}Ctrl+C${RESET} pour annuler."
```

Pour être sûr que les gens lisent qu'ils faut redémarrer. 

Voilà, des bisous. 

Cardiac.

**Comment by Xdavius** [comment]
yop.
Alors t'es pas OBLIGE de redémarrer desuite mais c'est recommandé (pour ne pas oublier le mot de passe XD)

J'ai un bug avec le terminal qui se ferme trop vite, faut que je règle ça.

Pour les couleurs faut que je fasse l'implatation script par script. D'abord je reglerais le délai avec un read pour bloquer la fenetre.

**Comment by Xdavius** [comment]
bloquage de la fenêtre fait
