### ISSUE TITLE
Précisions 2

### ISSUE THREAD

**Issue by Cardiacman13** [Xdavius/postinstall-debian#47]
Ajouter que Nvidia c'est >9xx Gtx.

Et, pourquoi pas, proposer des driver plus vieux pour les vielles Nvidia, si c'est possible.

**Comment by Xdavius** [comment]
faut que j'intègre le script de Nael pour la partie ancienne nvidia. 

Oui, faut que je précise pour GTX >930

**Comment by Xdavius** [comment]
fait
