### ISSUE TITLE
Améliorations

### ISSUE THREAD

**Issue by Cfrancky77** [Xdavius/postinstall-debian#49]
Bonjour,
J'aurais une petite liste en tant que débutant : 

- On ne sait pas trop quand il faut reboot, une indication sur le bouton serait top
- Dans la section autre : au bout d'un moment on ne sait plus trop ce qu'y a été installé. serait il possible d'avoir une case ou icone nous disant ok / nok (peut être en cliquant sur le bouton cela écrit dans un fichier texte par exemple).

**Comment by Xdavius** [comment]
Intéressant, MAIS le script doit être réutiliser après mise a niveau (pour mettre a jour les dépôts pour debian 13 quand il sera là.
A réfléchir comment implémenter un truc.

Pour le reboot, on est sur debian, donc on reboot une fois tout installé c'est bon. Soit après chaque driver comme sur windows, soit tout à la fin. Même pour sécureboot on est pas obligé de reboto dessuite même si c'est recommandé.

Normalement, dans le LOG de la GUI c'est marqué : Rebootez la machine. Je peux peut-être augmentrer le delai

**Comment by Xdavius** [comment]
> Bonjour, J'aurais une petite liste en tant que débutant :
> 
> * On ne sait pas trop quand il faut reboot, une indication sur le bouton serait top
> * Dans la section autre : au bout d'un moment on ne sait plus trop ce qu'y a été installé. serait il possible d'avoir une case ou icone nous disant ok / nok (peut être en cliquant sur le bouton cela écrit dans un fichier texte par exemple).

Intégration du reboot refaite.
